# This is a basic workflow to help you get started with Actions
name: Short Sleepy Matrix
run-name: Run short sleepy matrix on ${{ inputs.arc_name }}

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        arc_name:
          description: 'Target ARC name used for `runs-on` in job'
          required: true
          default: "ubuntu-20-04-16g-new"
        delay:
          description: 'how long to sleep in seconds'
          required: true
          default: "20"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-matrix:
    strategy:
       fail-fast: false
       matrix: 
         job: [1, 2, 3]
    runs-on: ${{ inputs.arc_name }}
    steps:
     - name: simple
       run: |
         echo "Hello from: " ${{ matrix.version }}
         sleep ${{ inputs.delay }}
    
  # This workflow contains a single job called "build"
  #build:
    # The type of runner that the job will run on
  #  runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # - uses: actions/checkout@v2

      # Runs a single command using the runners shell
     # - name: Run a one-line script
     #   run: echo Hello, world!

      # Runs docker hello-world
     # - name: Hello from Docker
     #   run: docker run hello-world
